theme = "monokai_risteretto_mod"
# theme = "pop-dark"
[editor]
auto-save = true
auto-format = true
auto-completion = true
bufferline = "multiple"
color-modes = true
line-number = "relative"
mouse = true
true-color = true

[editor.whitespace.render]
space = "none"
nbsp = "none"
tab = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
left = [ "mode", "file-name", "spacer", "diagnostics", ]
center = []
right = [
  "position", "separator",  "spacer", "position-percentage", "spacer", "separator", 
  "total-line-numbers", "separator",  "file-line-ending", "separator",  "file-type", ]
separator = "|"
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "╎"
skip-levels = 0

[editor.soft-wrap]
enable = true
max-wrap = 10 # increase value to reduce forced mid-word wrapping
max-indent-retain = 40

[keys.normal]
C-o = ":sh python IdeaProjects/CSE_110_Fall_2022-Practise/paractic.py"
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
esc = ["collapse_selection", "keep_primary_selection"]
y = "yank_joined_to_clipboard" # use my system clipboard
p = ["paste_clipboard_after", ":w"]
P = ["replace_selections_with_clipboard", ":w"] # paste over selection[keys.normal.backspace]
